### ISSUE TITLE
./launcher.sh: 39: Bad substitution

### ISSUE THREAD

**Issue by AshutoshGitMirror** [Git-Fal7/gtk-rofi#1]
``` 
gtk-rofi on  main [!] ❯ ./launcher.sh -show drun spotlight
All Good
./launcher.sh: 39: Bad substitution
gtk-rofi on  main [!] ❯ la
demo.mp4  .git  launcher.sh  README.md  scripts  settings.ini  templates  video.mkv

**Comment by rensenware** [comment]
Same issue.

**Comment by AshutoshGitMirror** [comment]
I will attach more system info in few minutes

**Comment by Git-Fal7** [comment]
Just looked into it, lines [39](https://github.com/Git-Fal7/gtk-rofi/blob/377d90f8e1630875f9c477ad6c4dc0a08bb512a6/launcher.sh#L39) & [43](https://github.com/Git-Fal7/gtk-rofi/blob/377d90f8e1630875f9c477ad6c4dc0a08bb512a6/launcher.sh#L43) aren't POSIX-complaint. They are used for providing the arguments to rofi.

**Comment by AshutoshGitMirror** [comment]
https://termbin.com/wwy5 here is system info

**Comment by AshutoshGitMirror** [comment]
> Just looked into it, lines [39](https://github.com/Git-Fal7/gtk-rofi/blob/377d90f8e1630875f9c477ad6c4dc0a08bb512a6/launcher.sh#L39) & [43](https://github.com/Git-Fal7/gtk-rofi/blob/377d90f8e1630875f9c477ad6c4dc0a08bb512a6/launcher.sh#L43) aren't POSIX-complaint. They are used for providing the arguments to rofi.

hmm is there any workaround for that?

**Comment by Git-Fal7** [comment]
@FallCheetah7373 and @rensenware could you test [36e6e5c](https://github.com/Git-Fal7/gtk-rofi/commit/36e6e5c824ba7718f69068ddc2525678f505cc9d)

**Comment by AshutoshGitMirror** [comment]
> @FallCheetah7373 and @rensenware could you test [36e6e5c](https://github.com/Git-Fal7/gtk-rofi/commit/36e6e5c824ba7718f69068ddc2525678f505cc9d)

the orginal issue with bad substitution is fixed but now I am facing some other issue.  I directly cloned the repo using the command in project description after removing the old one.

```
gtk-rofi on  main [!] took 6s ❯ ./launcher.sh -show run spotlight
Updating settings
./launcher.sh: 32: cannot create /home/fallcheetah7373/.config/rofi/gtk-rofi/themes/launchpad.rasi: Directory nonexistent
./launcher.sh: 32: cannot create /home/fallcheetah7373/.config/rofi/gtk-rofi/themes/spotlight.rasi: Directory nonexistent
Theme doesn't exist
gtk-rofi on  main [!] ❯ la
demo.mp4  .git  launcher.sh  README.md  scripts  settings.ini  templates  video.mkv
gtk-rofi on  main [!] ❯ cd templates/
gtk-rofi/templates on  main [!] ❯ la
launchpad.rasi  spotlight.rasi
gtk-rofi/templates on  main [!] ❯ cd ../
gtk-rofi on  main [!] ❯ ./launcher.sh -show run spotlight
All Good
Theme doesn't exist
```

**Comment by Git-Fal7** [comment]
@FallCheetah7373 create a folder called ``themes``

**Comment by Git-Fal7** [comment]
> > @FallCheetah7373 and @rensenware could you test [36e6e5c](https://github.com/Git-Fal7/gtk-rofi/commit/36e6e5c824ba7718f69068ddc2525678f505cc9d)
> 
> the orginal issue with bad substitution is fixed but now I am facing some other issue. I directly cloned the repo using the command in project description after removing the old one.
> 
> ```
> gtk-rofi on  main [!] took 6s ❯ ./launcher.sh -show run spotlight
> Updating settings
> ./launcher.sh: 32: cannot create /home/fallcheetah7373/.config/rofi/gtk-rofi/themes/launchpad.rasi: Directory nonexistent
> ./launcher.sh: 32: cannot create /home/fallcheetah7373/.config/rofi/gtk-rofi/themes/spotlight.rasi: Directory nonexistent
> Theme doesn't exist
> gtk-rofi on  main [!] ❯ la
> demo.mp4  .git  launcher.sh  README.md  scripts  settings.ini  templates  video.mkv
> gtk-rofi on  main [!] ❯ cd templates/
> gtk-rofi/templates on  main [!] ❯ la
> launchpad.rasi  spotlight.rasi
> gtk-rofi/templates on  main [!] ❯ cd ../
> gtk-rofi on  main [!] ❯ ./launcher.sh -show run spotlight
> All Good
> Theme doesn't exist
> ```

[bced50b](https://github.com/Git-Fal7/gtk-rofi/commit/bced50bdac069b5b6214a7a8834d59e72bfd4635) should fix the issue entirely

**Comment by AshutoshGitMirror** [comment]
> @FallCheetah7373 create a folder called `themes`

ok thanks the issue is resolved! I will close this issue.
